## Basic Numpy 

In [67]:
import numpy as np
%precision 3


'%.3f'

In [68]:
data = np.array([9,2,3,4,10,6,7,8,1,5])
data

array([ 9,  2,  3,  4, 10,  6,  7,  8,  1,  5])

In [69]:
print("dimention : ", data.ndim )
print("element : " , data.size)

dimention :  1
element :  10


In [70]:
data*2

array([18,  4,  6,  8, 20, 12, 14, 16,  2, 10])

In [71]:
print("Multiplication : ", np.array([1,2,3,4,5,6,7,8,9,10])*np.array([10,9,8,7,6,5,4,3,2,1]))
print("Square : ", np.array([1,2,3,4,5,6,7,8,9,10])**2)
print("Devision  :",np.array([1,2,3,4,5,6,7,8,9,10]) / np.array([10,9,8,7,6,5,4,3,2,1]))

Multiplication :  [10 18 24 28 30 30 28 24 18 10]
Square :  [  1   4   9  16  25  36  49  64  81 100]
Devision  : [ 0.1    0.222  0.375  0.571  0.833  1.2    1.75   2.667  4.5   10.   ]


In [72]:
data = np.array([9,2,3,4,10,6,7,8,1,5])
print(data)
data.sort()
print(data)
data[::-1].sort()
print(data)

[ 9  2  3  4 10  6  7  8  1  5]
[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


In [73]:
print("Min : ", min(data))
print("Max : ", max(data))
print("Sum : ", sum(data))
print("Mean:", sum(data)/data.size)
print("Cum : ", data.cumsum())
print("Ratio : ", data.cumsum()/data.sum())

Min :  1
Max :  10
Sum :  55
Mean: 5.5
Cum :  [10 19 27 34 40 45 49 52 54 55]
Ratio :  [0.182 0.345 0.491 0.618 0.727 0.818 0.891 0.945 0.982 1.   ]


In [74]:
import numpy.random as random

In [75]:
random.seed(0)

rnd_data = random.randn(10)
rnd_data

array([ 1.764,  0.4  ,  0.979,  2.241,  1.868, -0.977,  0.95 , -0.151,
       -0.103,  0.411])

In [76]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
#with Duplication
print(random.choice(data, 10))
#without Duplication
print(random.choice(data, 10, replace = False))

[ 7  8  8  9  2  6 10  9 10  5]
[ 5  2  7  8  3  9  6 10  1  4]


In [77]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [78]:
array1 = np.arange(9).reshape(3,3)
array2 = np.arange(9,18).reshape(3,3)
print(array1)
print("-----------")
print(array2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
-----------
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [79]:
np.dot(array1,array2)

array([[ 42,  45,  48],
       [150, 162, 174],
       [258, 279, 300]])

In [80]:
array1 * array2

array([[  0,  10,  22],
       [ 36,  52,  70],
       [ 90, 112, 136]])

In [81]:
print(np.zeros((2,3), dtype = np.int64))
print(np.ones((2,3), dtype = np.float64))

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]


# Appendix

In [82]:
import scipy.linalg as linalg
from scipy.optimize import minimize_scalar

In [83]:
matrix = np.array([[1,-1,-1],[-1,1,-1],[-1,-1,1]])
print(matrix)
print("det : ", linalg.det(matrix))

[[ 1 -1 -1]
 [-1  1 -1]
 [-1 -1  1]]
det :  -4.0


In [84]:
print("inverse", linalg.inv(matrix))

inverse [[ 0.  -0.5 -0.5]
 [-0.5 -0.  -0.5]
 [-0.5 -0.5  0. ]]


In [85]:
" dot product"
print(matrix.dot(linalg.inv(matrix)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [86]:
eig_value, eig_vector = linalg.eig(matrix)

print("Eigen Value : ",end="")
print(eig_value)
print("Eigen Vector",end="")
print(eig_vector)

Eigen Value : [-1.+0.j  2.+0.j  2.+0.j]
Eigen Vector[[ 0.577 -0.816  0.428]
 [ 0.577  0.408 -0.816]
 [ 0.577  0.408  0.389]]
